package buYanti;


import javax.swing.JOptionPane;
import java.text.SimpleDateFormat;
import java.text.ParseException;


/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author LENOVO
 */
public class KelolaData extends javax.swing.JFrame {
    private DashboardAdmin dashboard;
    private int editedRow = -1;
    /**
     * Creates new form KelolaData
     */
    public KelolaData(DashboardAdmin dashboard) {
        initComponents();
        setLocationRelativeTo(null);
        this.dashboard = dashboard;
        setTitle("Kelola Data - Laundry Bu Yanti");
    }
    
    public int Total_Harga;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel9 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        btn_dashboard = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txt_nama = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        combo_jenis = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        txt_berat = new javax.swing.JTextField();
        txt_harga = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txt_deadline = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txt_alamat = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/buYanti/Logo.png"))); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(110, 193, 228));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jList1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(34, 34, 34), 1, true));
        jList1.setFont(new java.awt.Font("Microsoft YaHei", 1, 14)); // NOI18N
        jList1.setForeground(new java.awt.Color(34, 34, 34));
        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "R: Reguler (3 hari)", "K: Kilat (2 hari)", "X: Express (1 hari)", "SX: Super Express (6 jam)", "S: Small", "M: Medium", "L: Large" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        btn_dashboard.setBackground(new java.awt.Color(110, 193, 228));
        btn_dashboard.setFont(new java.awt.Font("Microsoft YaHei", 1, 14)); // NOI18N
        btn_dashboard.setForeground(new java.awt.Color(255, 255, 255));
        btn_dashboard.setText("Add");
        btn_dashboard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_dashboardActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(btn_dashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_dashboard)
                .addGap(59, 59, 59))
        );

        jLabel1.setFont(new java.awt.Font("Microsoft YaHei", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Add Order List");

        jLabel2.setFont(new java.awt.Font("Microsoft YaHei", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Order Name");

        txt_nama.setFont(new java.awt.Font("Microsoft YaHei", 0, 14)); // NOI18N
        txt_nama.setForeground(new java.awt.Color(34, 34, 34));
        txt_nama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_namaActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Order Type");

        combo_jenis.setFont(new java.awt.Font("Microsoft YaHei", 0, 14)); // NOI18N
        combo_jenis.setForeground(new java.awt.Color(34, 34, 34));
        combo_jenis.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih jenis", "(R) Komplit", "(R) Cuci kering", "(R) Setrika", "(K) Komplit", "(K) Cuci kering", "(K) Setrika", "(X) Komplit", "(X) Cuci kering", "(X) Setrika", "(SX) Komplit", "(SX) Cuci kering", "(SX) Setrika", "Selimut (S)", "Selimut (M)", "Selimut (L)", "Bedcover (S)", "Bedcover (L)", "Sprei (S)", "Sprei (M)", "Sprei (L)", "Sepatu", "Helm" }));
        combo_jenis.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                combo_jenisItemStateChanged(evt);
            }
        });
        combo_jenis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combo_jenisActionPerformed(evt);
            }
        });
        combo_jenis.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                combo_jenisPropertyChange(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Weight");

        txt_berat.setFont(new java.awt.Font("Microsoft YaHei", 0, 14)); // NOI18N
        txt_berat.setForeground(new java.awt.Color(34, 34, 34));
        txt_berat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_beratActionPerformed(evt);
            }
        });
        txt_berat.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_beratKeyReleased(evt);
            }
        });

        txt_harga.setFont(new java.awt.Font("Microsoft YaHei", 0, 14)); // NOI18N
        txt_harga.setForeground(new java.awt.Color(34, 34, 34));
        txt_harga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_hargaActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Price");

        txt_deadline.setFont(new java.awt.Font("Microsoft YaHei", 0, 14)); // NOI18N
        txt_deadline.setForeground(new java.awt.Color(34, 34, 34));
        txt_deadline.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_deadlineActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Deadline");

        txt_alamat.setFont(new java.awt.Font("Microsoft YaHei", 0, 14)); // NOI18N
        txt_alamat.setForeground(new java.awt.Color(34, 34, 34));
        txt_alamat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_alamatActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Addres");

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/buYanti/Logo.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel11)
                            .addComponent(jLabel13))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_nama)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txt_harga)
                                    .addComponent(combo_jenis, 0, 178, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel10))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txt_deadline, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE)
                                    .addComponent(txt_berat)))
                            .addComponent(txt_alamat))))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel4))
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txt_nama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(combo_jenis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(txt_berat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_harga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(txt_deadline, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_alamat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addContainerGap(65, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_beratActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_beratActionPerformed
        String input = txt_berat.getText();
        if (!input.matches("\\d+")) {
            JOptionPane.showMessageDialog(null, "Mohon masukkan angka", "Tidak menerima data tersebut", JOptionPane.ERROR_MESSAGE);
        } else {
            if (txt_berat.getText().equals("")) {
            txt_harga.setText("0");
            } else {
                int harga = Integer.parseInt(txt_harga.getText());
                int berat = Integer.parseInt(txt_berat.getText());
                int Total_Harga = harga * berat;
                txt_harga.setText(String.valueOf(Total_Harga));
            }
        }
    }//GEN-LAST:event_txt_beratActionPerformed

    private void combo_jenisItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_combo_jenisItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_combo_jenisItemStateChanged

    private void combo_jenisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combo_jenisActionPerformed
        if (combo_jenis.getSelectedItem().equals("(R) Komplit")) {
            txt_harga.setText("6000");
        } else if (combo_jenis.getSelectedItem().equals("(R) Cuci kering")) {
            txt_harga.setText("5000");
        } else if (combo_jenis.getSelectedItem().equals("(R) Setrika")) {
            txt_harga.setText("5000");
        } else if (combo_jenis.getSelectedItem().equals("(K) Komplit")) {
            txt_harga.setText("7500");
        } else if (combo_jenis.getSelectedItem().equals("(K) Cuci kering")) {
            txt_harga.setText("7000");
        } else if (combo_jenis.getSelectedItem().equals("(K) Setrika")) {
            txt_harga.setText("7000");
        } else if (combo_jenis.getSelectedItem().equals("(X) Komplit")) {
            txt_harga.setText("10000");
        } else if (combo_jenis.getSelectedItem().equals("(X) Cuci kering")) {
            txt_harga.setText("9000");
        } else if (combo_jenis.getSelectedItem().equals("(X) Setrika")) {
            txt_harga.setText("9000");
        } else if (combo_jenis.getSelectedItem().equals("(SX) Komplit")) {
            txt_harga.setText("15000");
        } else if (combo_jenis.getSelectedItem().equals("(SX) Cuci kering")) {
            txt_harga.setText("14000");
        } else if (combo_jenis.getSelectedItem().equals("(SX) Setrika")) {
            txt_harga.setText("14000");
        } else if (combo_jenis.getSelectedItem().equals("Selimut (S)")) {
            txt_harga.setText("15000");
        } else if (combo_jenis.getSelectedItem().equals("Selimut (M)")) {
            txt_harga.setText("20000");
        } else if (combo_jenis.getSelectedItem().equals("Selimut (L)")) {
            txt_harga.setText("25000");
        } else if (combo_jenis.getSelectedItem().equals("Bedcover (L)")) {
            txt_harga.setText("30000");
        } else if (combo_jenis.getSelectedItem().equals("Bedcover (S)")) {
            txt_harga.setText("25000");
        } else if (combo_jenis.getSelectedItem().equals("Sprei (S)")) {
            txt_harga.setText("7500");
        } else if (combo_jenis.getSelectedItem().equals("Sprei (M)")) {
            txt_harga.setText("10000");
        } else if (combo_jenis.getSelectedItem().equals("Sprei (L)")) {
            txt_harga.setText("15000");
        } else if (combo_jenis.getSelectedItem().equals("Sepatu")) {
            txt_harga.setText("25000");
        } else if (combo_jenis.getSelectedItem().equals("Helm")) {
            txt_harga.setText("25000");
        } else {
            txt_harga.setText("0");
        }
    }//GEN-LAST:event_combo_jenisActionPerformed

    private void combo_jenisPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_combo_jenisPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_combo_jenisPropertyChange

    private void txt_namaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_namaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_namaActionPerformed

    private void txt_hargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_hargaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_hargaActionPerformed

    private void txt_deadlineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_deadlineActionPerformed

    }//GEN-LAST:event_txt_deadlineActionPerformed

    private void txt_alamatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_alamatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_alamatActionPerformed

    private void txt_beratKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_beratKeyReleased
        if(txt_berat.getText().equals("")){
            txt_harga.setText("0");
        } else{
            int harga = Integer.parseInt(txt_harga.getText());
            int berat = Integer.parseInt(txt_berat.getText());
            Total_Harga = harga * berat;
            txt_harga.setText(String.valueOf(Total_Harga));
        }
    }//GEN-LAST:event_txt_beratKeyReleased

    private void btn_dashboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_dashboardActionPerformed
        String nama = txt_nama.getText();
        String layanan = combo_jenis.getSelectedItem().toString();
        String alamat = txt_alamat.getText();
        String harga = txt_harga.getText();
        String deadline = txt_deadline.getText();
        String berat = txt_berat.getText();
        
        Object[] rowData = { nama, layanan, alamat, harga, deadline };
        
        if(!deadline.matches("\\d{2}/\\d{2}/\\d{4}")) {
            JOptionPane.showMessageDialog(null, "Format deadline harus dd/MM/yyyy", "Tidak menerima data tersebut", JOptionPane.ERROR_MESSAGE);
        } else if(!berat.matches("\\d+")) {
            JOptionPane.showMessageDialog(null, "Mohon masukkan angka pada kolom berat", "Tidak menerima data tersebut", JOptionPane.ERROR_MESSAGE);
        } else {
            if (editedRow >= 0){
                dashboard.getTable().setValueAt(nama, editedRow, 0);
                dashboard.getTable().setValueAt(layanan, editedRow, 1);
                dashboard.getTable().setValueAt(alamat, editedRow, 2);
                dashboard.getTable().setValueAt(harga, editedRow, 3);
                dashboard.getTable().setValueAt(deadline, editedRow, 4);
                dashboard.setVisible(true);
                dispose();
            } else {
                dashboard.tambahDataKeTabel(rowData);
                dashboard.setVisible(true);
                dispose();
            }
        }
    }//GEN-LAST:event_btn_dashboardActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KelolaData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KelolaData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KelolaData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KelolaData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            DashboardAdmin dashboard = new DashboardAdmin();
            KelolaData kelola = new KelolaData(dashboard);
            kelola.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_dashboard;
    private javax.swing.JComboBox<String> combo_jenis;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txt_alamat;
    private javax.swing.JTextField txt_berat;
    private javax.swing.JTextField txt_deadline;
    private javax.swing.JTextField txt_harga;
    private javax.swing.JTextField txt_nama;
    // End of variables declaration//GEN-END:variables

    public void setData(String nama, String layanan, String alamat, String harga, String deadline, int row) {
        txt_nama.setText(nama);
        combo_jenis.setSelectedItem(layanan);
        txt_alamat.setText(alamat);
        txt_harga.setText(harga);
        txt_deadline.setText(deadline);
        this.editedRow = row;
        
    }
}
