package buYanti;


import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author LENOVO
 */
public class KelolaData extends javax.swing.JFrame {
    private DashboardAdmin dashboard;
    private int editedRow = -1;
    /**
     * Creates new form KelolaData
     */
    public KelolaData(DashboardAdmin dashboard) {
        initComponents();
        this.dashboard = dashboard;
        setTitle("Kelola Data - Laundry Bu Yanti");
    }
    
    public int Total_Harga;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txt_berat = new javax.swing.JTextField();
        combo_jenis = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        txt_nama = new javax.swing.JTextField();
        txt_harga = new javax.swing.JTextField();
        txt_deadline = new javax.swing.JTextField();
        txt_alamat = new javax.swing.JTextField();
        btn_dashboard = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        jLabel1.setText("Tambahkan List Pekerjaan");

        jLabel2.setText("Nama Client");

        jLabel3.setText("Jenis Layanan");

        jLabel4.setText("Berat");

        jLabel5.setText("Harga");

        jLabel6.setText("Deadline");

        txt_berat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_beratActionPerformed(evt);
            }
        });
        txt_berat.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_beratKeyReleased(evt);
            }
        });

        combo_jenis.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih jenis", "(R) Komplit", "(R) Cuci kering", "(R) Setrika", "(K) Komplit", "(K) Cuci kering", "(K) Setrika", "(X) Komplit", "(X) Cuci kering", "(X) Setrika", "(SX) Komplit", "(SX) Cuci kering", "(SX) Setrika", "Selimut (S)", "Selimut (M)", "Selimut (L)", "Bedcover (S)", "Bedcover (L)", "Sprei (S)", "Sprei (M)", "Sprei (L)", "Sepatu", "Helm" }));
        combo_jenis.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                combo_jenisItemStateChanged(evt);
            }
        });
        combo_jenis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combo_jenisActionPerformed(evt);
            }
        });
        combo_jenis.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                combo_jenisPropertyChange(evt);
            }
        });

        jLabel7.setText("Alamat");

        txt_nama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_namaActionPerformed(evt);
            }
        });

        txt_harga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_hargaActionPerformed(evt);
            }
        });

        txt_deadline.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_deadlineActionPerformed(evt);
            }
        });

        txt_alamat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_alamatActionPerformed(evt);
            }
        });

        btn_dashboard.setText("Dashboard");
        btn_dashboard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_dashboardActionPerformed(evt);
            }
        });

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "R: Reguler (3 hari)", "K: Kilat (2 hari)", "X: Express (1 hari)", "SX: Super Express (6 jam)", "S: Small", "M: Medium", "L: Large" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        jLabel8.setText("Note:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(180, 180, 180)
                .addComponent(btn_dashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(149, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(147, 147, 147))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txt_nama, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txt_harga, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4)
                        .addComponent(combo_jenis, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5)
                        .addComponent(txt_berat, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3)
                        .addComponent(txt_alamat, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel7)
                        .addComponent(txt_deadline, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel6)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txt_nama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(combo_jenis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_berat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_harga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_alamat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_deadline, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addComponent(btn_dashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(46, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_beratActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_beratActionPerformed
        if(txt_berat.getText().equals("")){
            txt_harga.setText("0");
        } else{
            int harga = Integer.parseInt(txt_harga.getText());
            int berat = Integer.parseInt(txt_berat.getText());
            Total_Harga = harga * berat;
            txt_harga.setText(String.valueOf(Total_Harga));
        }
    }//GEN-LAST:event_txt_beratActionPerformed

    private void combo_jenisItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_combo_jenisItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_combo_jenisItemStateChanged

    private void combo_jenisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combo_jenisActionPerformed
        if (combo_jenis.getSelectedItem().equals("(R) Komplit")) {
            txt_harga.setText("6000");
        } else if (combo_jenis.getSelectedItem().equals("(R) Cuci kering")) {
            txt_harga.setText("5000");
        } else if (combo_jenis.getSelectedItem().equals("(R) Setrika")) {
            txt_harga.setText("5000");
        } else if (combo_jenis.getSelectedItem().equals("(K) Komplit")) {
            txt_harga.setText("7500");
        } else if (combo_jenis.getSelectedItem().equals("(K) Cuci kering")) {
            txt_harga.setText("7000");
        } else if (combo_jenis.getSelectedItem().equals("(K) Setrika")) {
            txt_harga.setText("7000");
        } else if (combo_jenis.getSelectedItem().equals("(X) Komplit")) {
            txt_harga.setText("10000");
        } else if (combo_jenis.getSelectedItem().equals("(X) Cuci kering")) {
            txt_harga.setText("9000");
        } else if (combo_jenis.getSelectedItem().equals("(X) Setrika")) {
            txt_harga.setText("9000");
        } else if (combo_jenis.getSelectedItem().equals("(SX) Komplit")) {
            txt_harga.setText("15000");
        } else if (combo_jenis.getSelectedItem().equals("(SX) Cuci kering")) {
            txt_harga.setText("14000");
        } else if (combo_jenis.getSelectedItem().equals("(SX) Setrika")) {
            txt_harga.setText("14000");
        } else if (combo_jenis.getSelectedItem().equals("Selimut (S)")) {
            txt_harga.setText("15000");
        } else if (combo_jenis.getSelectedItem().equals("Selimut (M)")) {
            txt_harga.setText("20000");
        } else if (combo_jenis.getSelectedItem().equals("Selimut (L)")) {
            txt_harga.setText("25000");
        } else if (combo_jenis.getSelectedItem().equals("Bedcover (L)")) {
            txt_harga.setText("30000");
        } else if (combo_jenis.getSelectedItem().equals("Bedcover (S)")) {
            txt_harga.setText("25000");
        } else if (combo_jenis.getSelectedItem().equals("Sprei (S)")) {
            txt_harga.setText("7500");
        } else if (combo_jenis.getSelectedItem().equals("Sprei (M)")) {
            txt_harga.setText("10000");
        } else if (combo_jenis.getSelectedItem().equals("Sprei (L)")) {
            txt_harga.setText("15000");
        } else if (combo_jenis.getSelectedItem().equals("Sepatu")) {
            txt_harga.setText("25000");
        } else if (combo_jenis.getSelectedItem().equals("Helm")) {
            txt_harga.setText("25000");
        } else {
            txt_harga.setText("0");
        }
    }//GEN-LAST:event_combo_jenisActionPerformed

    private void combo_jenisPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_combo_jenisPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_combo_jenisPropertyChange

    private void txt_namaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_namaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_namaActionPerformed

    private void txt_hargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_hargaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_hargaActionPerformed

    private void txt_deadlineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_deadlineActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_deadlineActionPerformed

    private void txt_alamatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_alamatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_alamatActionPerformed

    private void txt_beratKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_beratKeyReleased
        if(txt_berat.getText().equals("")){
            txt_harga.setText("0");
        } else{
            int harga = Integer.parseInt(txt_harga.getText());
            int berat = Integer.parseInt(txt_berat.getText());
            Total_Harga = harga * berat;
            txt_harga.setText(String.valueOf(Total_Harga));
        }
    }//GEN-LAST:event_txt_beratKeyReleased

    private void btn_dashboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_dashboardActionPerformed
        String nama = txt_nama.getText();
        String layanan = combo_jenis.getSelectedItem().toString();
        String alamat = txt_alamat.getText();
        String harga = txt_harga.getText();
        String deadline = txt_deadline.getText();
        
        Object[] rowData = { nama, layanan, alamat, harga, deadline };

        
        if (editedRow >= 0){
            dashboard.getTable().setValueAt(nama, editedRow, 0);
            dashboard.getTable().setValueAt(layanan, editedRow, 1);
            dashboard.getTable().setValueAt(alamat, editedRow, 2);
            dashboard.getTable().setValueAt(harga, editedRow, 3);
            dashboard.getTable().setValueAt(deadline, editedRow, 4);
        } else {
            dashboard.tambahDataKeTabel(rowData);
        }
        dashboard.setVisible(true);
        dispose();
    }//GEN-LAST:event_btn_dashboardActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KelolaData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KelolaData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KelolaData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KelolaData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            DashboardAdmin dashboard = new DashboardAdmin();
            KelolaData kelola = new KelolaData(dashboard);
            kelola.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_dashboard;
    private javax.swing.JComboBox<String> combo_jenis;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txt_alamat;
    private javax.swing.JTextField txt_berat;
    private javax.swing.JTextField txt_deadline;
    private javax.swing.JTextField txt_harga;
    private javax.swing.JTextField txt_nama;
    // End of variables declaration//GEN-END:variables

    public void setData(String nama, String layanan, String alamat, String harga, String deadline, int row) {
        txt_nama.setText(nama);
        combo_jenis.setSelectedItem(layanan);
        txt_alamat.setText(alamat);
        txt_harga.setText(harga);
        txt_deadline.setText(deadline);
        this.editedRow = row;
        
    }
}
